### ISSUE TITLE
where are the ***.h5? 

### ISSUE THREAD

**Issue by xiaoma2223** [TIMOLEEGO/LSC-CNN#1]
where are the ***.h5? Could you please upload them? Thank you?

**Comment by TIMOLEEGO** [comment]
The link to the dataset will be posted soon.

**Comment by xiaoma2223** [comment]
thanks! !!!


1779295491
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TIMOLEEGO/LSC-CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月14日(星期四) 晚上8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TIMOLEEGO/LSC-CNN] where are the ***.h5?  (Issue #1)





 
The link to the dataset will be posted soon.

**Comment by xiaoma2223** [comment]
could u please upload the utils.py ?The current code is incomplete.thank you so much
